import { User } from './user';

export const USERS: User[] = [
  {
    id: 1,
    email: 'cypher@email.com',
    password: 'password123',
    firstName: 'Amir',
    lastName: 'El-Amari',
    country: 'Indonesia',
    city: 'Jakarta',
    company: 'Lithan',
    picture: '../assets/images/user/user3.jpg',
    banner: '../assets/images/user/banner/banner1.jpg',
  },
  {
    id: 2,
    email: 'antonov@email.com',
    password: 'password123',
    firstName: 'Pankratiyv',
    lastName: 'Antonov',
    country: 'Russia',
    city: 'Moscow',
    company: 'Google',
    picture: '../assets/images/user/user2.jpg',
    banner: '../assets/images/user/banner/banner2.jpg',
  },
  {
    id: 3,
    email: 'mirna@email.com',
    password: 'password123',
    firstName: 'Jabeehah',
    lastName: 'Hussein',
    country: 'Saudi Arabia',
    city: 'Riyadh',
    company: 'Buroq Online',
    picture: '../assets/images/user/user1.jpg',
    banner: '../assets/images/user/banner/banner3.jpg',
  },
  {
    id: 4,
    email: 'Ncull@email.com',
    password: '123456',
    firstName: 'Ncull',
    lastName: 'Purnama',
    country: 'Iceland',
    city: 'Reykjavík',
    company: 'Hilton Reykjavik Nordica',
    picture: '../assets/images/user/user4.jpg',
    banner: '../assets/images/user/banner/banner4.jpg',
  },
];  