/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-08 15:39:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_002dresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Documents/minchul/kuliah/Modul%206/Assignment%202/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/abc-jobs-spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1662647482048L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662603590288L));
    _jspx_dependants.put("/WEB-INF/views/navbar.jsp", Long.valueOf(1662645454404L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>ABC Jobs</title>\n");
      out.write("\n");
      out.write("<link href=\"https://bootswatch.com/5/lux/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("' rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("' rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("' rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary shadow py-3 px-5 mb-4\">\n");
      out.write("   <div class=\"container-fluid\">\n");
      out.write("     <a class=\"navbar-brand\" href=\"#\">ABC Jobs</a>\n");
      out.write("     <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("       <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("     </button>\n");
      out.write("     <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("       <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("         <li class=\"nav-item\">\n");
      out.write("           <a class=\"nav-link\" aria-current=\"page\" routerLink=\"/\">Home</a>\n");
      out.write("         </li>\n");
      out.write("         <li class=\"nav-item\">\n");
      out.write("           <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/search\">Search</a>\n");
      out.write("         </li>\n");
      out.write("       </ul>\n");
      out.write("       <div>\n");
      out.write("         <a href=\"");
      out.print( request.getContextPath() );
      out.write("/login\"><button class=\"btn btn-light\" type=\"button\">Login</button></a>\n");
      out.write("         <a href=\"");
      out.print( request.getContextPath() );
      out.write("/registration\"><button class=\"btn btn-light\" type=\"button\">Sign Up</button></a>\n");
      out.write("       </div>\n");
      out.write("     </div>\n");
      out.write("   </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("		<h5 style=\"margin-left: 10vw\">Search result</h5>\n");
      out.write("		<div class=\"result\">\n");
      out.write("		    <div>\n");
      out.write("		        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/profile\">\n");
      out.write("		        <div class=\"container card d-flex flex-row w-50 mb-3\" >\n");
      out.write("		            <div class=\"photoprofile\"><img src=\"resources/img/user-default.png\" alt=\"Photo Profile\"></div>\n");
      out.write("		            <div class=\"ms-5 d-flex flex-column justify-content-center\">\n");
      out.write("		                <h3>Viddy Virstandi P.A.P</h3>\n");
      out.write("		                <h4>Lithan</h4>\n");
      out.write("		                <p>Lithan learners<p>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		        </a>\n");
      out.write("		    </div>\n");
      out.write("		    <div>\n");
      out.write("		        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/profile\">\n");
      out.write("		        <div class=\"container card d-flex flex-row w-50 mb-3\" >\n");
      out.write("		            <div class=\"photoprofile\"><img src=\"resources/img/user-default.png\" alt=\"Photo Profile\"></div>\n");
      out.write("		            <div class=\"ms-5 d-flex flex-column justify-content-center\">\n");
      out.write("		                <h3>Amir El-Amari</h3>\n");
      out.write("		                <h4>Lithan</h4>\n");
      out.write("		                <p>Lithan Mentor<p>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		        </a>\n");
      out.write("		    </div>\n");
      out.write("		    <div>\n");
      out.write("		        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/profile\">\n");
      out.write("		        <div class=\"container card d-flex flex-row w-50 mb-3\" >\n");
      out.write("		            <div class=\"photoprofile\"><img src=\"resources/img/user-default.png\" alt=\"Photo Profile\"></div>\n");
      out.write("		            <div class=\"ms-5 d-flex flex-column justify-content-center\">\n");
      out.write("		                <h3>Alexander Novikov</h3>\n");
      out.write("		                <h4>Google</h4>\n");
      out.write("		                <p>Front End Developer<p>\n");
      out.write("		            </div>\n");
      out.write("		        </div>\n");
      out.write("		        </a>\n");
      out.write("		    </div>\n");
      out.write("		</div>\n");
      out.write("	");
      out.write("	<section id=\"footer\" class=\"mt-5\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"footer-content d-flex flex-column flex-md-row\">\n");
      out.write("        <div class=\"footer-brand me-5 pe-lg-5 mb-2\">\n");
      out.write("          <h2 class=\"fw-semibold\">ABC Jobs</h2>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-links d-flex justify-content-between flex-wrap text-primary\">\n");
      out.write("          <ul class=\"links text-primary\" style=\"list-style-type= none\">\n");
      out.write("            <span class=\"fw-semibold text-primary\">General</span>\n");
      out.write("            <li><p class=\"text-primary\">Sign up</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Help center</p></li>\n");
      out.write("            <li><p class=\"text-primary\">About</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Developers</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Careers</p></li>\n");
      out.write("          </ul>\n");
      out.write("          <ul class=\"links\">\n");
      out.write("            <span class=\"fw-semibold\" style=\"list-style-type= none\">Directories</span>\n");
      out.write("            <li><p class=\"text-primary\">Jobs</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Articles</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Companies</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Topics</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Featured</p></li>\n");
      out.write("          </ul>\n");
      out.write("          <ul class=\"links\">\n");
      out.write("            <span class=\"fw-semibold\" style=\"list-style-type= none\">Follow us</span>\n");
      out.write("            <li><p class=\"text-primary\">Twitter</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Facebook</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Instagram</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Youtube</p></li>\n");
      out.write("          </ul>\n");
      out.write("          <ul class=\"links\">\n");
      out.write("            <span class=\"fw-semibold\" style=\"list-style-type= none\">Legal</span>\n");
      out.write("            <li><p class=\"text-primary\">Privacy policy</p></li>\n");
      out.write("            <li><p class=\"text-primary\">Terms of service</p></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <p class=\"mt-2\">ABC Jobs 2022. All Rights Reserved</p>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/search-result.jsp(11,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("resources/css/navbar.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/search-result.jsp(12,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("resources/css/footer.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/search-result.jsp(13,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("resources/css/search-result.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
